# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

TEMP_KEYCHAIN_PASSWORD = ENV["TEMP_KEYCHAIN_PASSWORD"]
TEMP_KEYCHAIN_NAME = "fastlane_tmp_keychain"

platform :ios do

  private_lane :remove_temp_keychain do |options|
    begin 
      next if !is_ci
      name = options[:name].nil? ? TEMP_KEYCHAIN_NAME : options[:name]
      delete_keychain(
        name: name
      ) if File.exist? File.expand_path("~/Library/Keychains/#{name}-db")
    rescue => ex
      puts(ex)
    end
  end

  lane :certs do

    app_store_connect_api_key()

    remove_temp_keychain

    # setup_ci if is_ci
    
    setup_jenkins(
        unlock_keychain: true,
        keychain_password: TEMP_KEYCHAIN_PASSWORD,
        output_directory: ENV["OUTPUT_FILES_PATH"],
        add_keychain_to_search_list: true
        # set_code_signing_identity: false,
        # set_default_keychain: false
    ) if is_ci
    

    cocoapods(clean_install: is_ci)

    update_code_signing_settings(
        use_automatic_signing: false,
        path: "../ios/Runner.xcodeproj",
        code_sign_identity: "iPhone Distribution",
        # profile_name: "match AppStore com.appbundle.id",
        # bundle_identifier: "com.appbundle.id"
    )

    match(
        app_identifier: CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier), 
        type: 'appstore', 
        readonly: is_ci,
        output_path: ENV["OUTPUT_FILES_PATH"],
        force_for_new_devices: true,
        verbose: true,
        # keychain_name: TEMP_KEYCHAIN_NAME,
        # keychain_password: TEMP_KEYCHAIN_PASSWORD
    )

    # Get a new certificate for push notifications
    get_push_certificate( 
        output_path: ENV["OUTPUT_FILES_PATH"]
    )

    # Create or get certificate, and install it
    get_certificates( 
        output_path: ENV["OUTPUT_FILES_PATH"]
    )

    # Create or get provisioning profile
    get_provisioning_profile( 
      output_path: ENV["OUTPUT_FILES_PATH"],
      filename: "app.mobileprovision"
    )

    # Set the project provisioning profile (related in Xcode to the General > Signing Release section)
    update_project_provisioning( 
      xcodeproj: "Runner.xcodeproj",
      target_filter: ENV['APP_NAME'], # Name of your project
      profile: "app.mobileprovision",
      build_configuration: "Release"
    )

    # Set the right team on your project
    update_project_team( 
      teamid: CredentialsManager::AppfileConfig.try_fetch_value(:team_id)
    )

    gym
  end

  private_lane :build do
    
    puts "build process started..."

    # Ensure that the git status is clean and no megre head or un-commited code exists
    # ensure_git_status_clean

    # RUN LANE TO GET CERTS
    # certs

    # INCREMENT BUILD NUMBER
    increment_build_number(xcodeproj: "Runner.xcodeproj")

    #Release notes - If empty will show last git commits in the notes
    if release_notes.empty?
      # Fetch changelog from Git repo
      release_notes = changelog_from_git_commits(
                          commits_count: "10",
                          pretty: "- (%ae) %s",
                          date_format: "short",
                          match_lightweight_tag: false, 
                          merge_commit_filtering: "exclude_merges")
    end    

    # Commit the version bump
    # commit_version_bump(xcodeproj: "Runner.xcodeproj")

    # Add a git tag for this build. This will automatically
    # use an appropriate git tag name
    # add_git_tag

    # Push the new commit and tag back to your git remote
    # push_to_git_remote

    # BUILD APP
    build_app(
        workspace: "Runner.xcworkspace", 
        scheme: "Runner",
        clean: true,
        export_method: "app-store",
        build_path: ENV["OUTPUT_FILES_PATH"],
        output_directory: ENV["OUTPUT_FILES_PATH"]
    )

  end

  desc "Push a new beta build to TestFlight"
  lane :beta do

    # RUN BUILD LANE
    build

    # GET GIT CHANGELOG
    # changelog_from_git_commits
    
    # UPLOAD TO TEST FLIGTH
    pilot(
      skip_waiting_for_build_processing: true,
      skip_submission: true,
      distribute_external: false,
      notify_external_testers: false,
      changelog: release_notes
    )
    
  end
  
end
