# https://github.com/GitTools/actions/blob/main/docs/examples/github/gitversion/execute/usage-examples.md

name: Generate semantic version

on:
  pull_request:
    branches:
      - 'release/**'
      - 'main'
    types:
      - closed

jobs:
  generate-version:
    if: github.event.pull_request.merged == true
    name: Generate Version
    runs-on: ubuntu-latest
    outputs:
      branchName: ${{ steps.gitversion.outputs.branchName }}
      semVer: ${{ steps.gitversion.outputs.semVer }}
      shortSha: ${{ steps.gitversion.outputs.shortSha }}
      tagName: ${{ steps.generate-tag.outputs.tagName }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.15
        with:
          versionSpec: '5.x'

      - name: Determine Version
        id:   gitversion
        uses: gittools/actions/gitversion/execute@v0.9.15

      - name: Create new tag
        id:   generate-tag
        run: |
          # TAG_NAME=$GITVERSION_SEMVER-$GITVERSION_SHORTSHA
          TAG_NAME=$GITVERSION_MAJORMINORPATCH$GITVERSION_PRERELEASELABELWITHDASH.${GITHUB_RUN_NUMBER}-$GITVERSION_SHORTSHA
          echo "tagName=$TAG_NAME" >> $GITHUB_OUTPUT
          git tag $TAG_NAME
          git push origin $TAG_NAME


  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: generate-version
    if: github.event.pull_request.merged == true && contains(needs.generate-version.outputs.branchName, 'main')
    steps:
      - run: |
          echo "Creating release notes for ${{ needs.generate-version.outputs.branchName }} branch."
          # https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#create-a-release
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${GITHUB_REPOSITORY}/releases \
            -d '{"tag_name":"${{ needs.generate-version.outputs.tagName }}", "name": "v${{ needs.generate-version.outputs.semVer }}","generate_release_notes":true}'